# 常量定义
SOURCE_ARXIV = 'arxiv'
SOURCE_HACKER_NEWS = 'hacker_news'
SOURCE_HUGGINGFACE_PAPERS = 'huggingface_papers'
SOURCE_TECHCRUNCH = 'tech_crunch'
SOURCE_GITHUB_TRENDING = 'github_trending'
SOURCES = [SOURCE_ARXIV, SOURCE_HACKER_NEWS, SOURCE_HUGGINGFACE_PAPERS, SOURCE_TECHCRUNCH, SOURCE_GITHUB_TRENDING]

# 推送目标
PUSH_ENDPOINT_EMAIL = 'email'
PUSH_ENDPOINT_WECHAT = 'wechat'
PUSH_ENDPOINTS = [PUSH_ENDPOINT_EMAIL, PUSH_ENDPOINT_WECHAT]
